# Generated by Django 5.0.7 on 2024-11-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0010_remove_worksession_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='confirmation_passcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password_reset_requested',
            field=models.BooleanField(default=False),
        ),
    ]
